#!/usr/bin/env bash
# Send p1 and p2 alerts to a Telegram chat as well as to the local sink.
#
# Once, by hand, in Telegram:
#   1. talk to @BotFather, send /newbot, follow it, copy the token it gives you
#   2. open the new bot's chat and send it any message (a bot cannot write to you first)
# Then:
#   scripts/telegram-setup.sh            # asks for the token without echoing it
#
# The token and the chat id go into monitoring/secrets/ (not in the repository), a local
# Alertmanager config is generated from the committed one, and Alertmanager is restarted on it.
# Undo: delete monitoring/.env and run `docker compose up -d alertmanager` in monitoring/.
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
secrets="$root/monitoring/secrets"
base="$root/monitoring/metrics/alertmanager/alertmanager.yml"
local_cfg="$root/monitoring/metrics/alertmanager/alertmanager.local.yml"
api=https://api.telegram.org

token=${TELEGRAM_BOT_TOKEN:-}
if [ -z "$token" ] && [ -s "$secrets/telegram_token" ]; then token=$(cat "$secrets/telegram_token"); fi
if [ -z "$token" ]; then read -r -s -p "Bot token from @BotFather: " token; echo; fi
[ -n "$token" ] || { echo "no token given"; exit 1; }

me=$(curl -fsS -m 15 "$api/bot$token/getMe") || { echo "Telegram rejected the token"; exit 1; }
echo "bot: @$(printf '%s' "$me" | python3 -c 'import sys,json; print(json.load(sys.stdin)["result"]["username"])')"

chat=$(curl -fsS -m 15 "$api/bot$token/getUpdates" | python3 -c '
import sys, json
ids = [u["message"]["chat"]["id"] for u in json.load(sys.stdin)["result"] if "message" in u]
print(ids[-1] if ids else "")')
[ -n "$chat" ] || { echo "The bot has no messages yet. Open its chat in Telegram, send it anything, and run this again."; exit 1; }
echo "chat id: $chat"

mkdir -p "$secrets"
umask 077
printf '%s' "$token" > "$secrets/telegram_token"
printf '%s' "$chat" > "$secrets/telegram_chat_id"
chmod 644 "$secrets/telegram_token" "$secrets/telegram_chat_id"   # read by the container's own user

python3 - "$base" "$local_cfg" <<'PY'
import sys
base, out = sys.argv[1:3]
s = open(base).read()
route = '''  routes:
    # p1 and p2 also go to Telegram; `continue` lets the routes below deliver to the sink as well.
    - matchers:
        - severity =~ "p1|p2"
      receiver: telegram
      group_wait: 10s
      repeat_interval: 1h
      continue: true

'''
receiver = '''receivers:
  - name: telegram
    telegram_configs:
      - bot_token_file: /etc/alertmanager/secrets/telegram_token
        chat_id_file: /etc/alertmanager/secrets/telegram_chat_id
        send_resolved: true
        parse_mode: ""
        message: |-
          {{ range .Alerts }}[{{ .Status | toUpper }}] {{ .Labels.severity }} {{ .Labels.alertname }}
          {{ .Annotations.summary }}
          {{ end }}
'''
assert "  routes:\n" in s and "receivers:\n" in s
s = s.replace("  routes:\n", route, 1).replace("receivers:\n", receiver, 1)
open(out, "w").write("# Generated by scripts/telegram-setup.sh from alertmanager.yml. Do not edit; run the script again.\n" + s)
PY

env="$root/monitoring/.env"
grep -v '^ALERTMANAGER_CONFIG=' "$env" 2>/dev/null > "$env.tmp" || true
echo "ALERTMANAGER_CONFIG=alertmanager.local.yml" >> "$env.tmp"
mv "$env.tmp" "$env"

(cd "$root/monitoring" && docker compose up -d alertmanager >/dev/null)
docker exec sol-alertmanager amtool check-config /etc/alertmanager/config/alertmanager.local.yml >/dev/null
curl -fsS -m 15 "$api/bot$token/sendMessage" --data-urlencode "chat_id=$chat" \
  --data-urlencode "text=Solana lab: alerts are connected. p1 and p2 will arrive here." >/dev/null
echo "done: a test message was sent, and Alertmanager now delivers p1 and p2 to this chat"
